#! /usr/bin/bash

_unzip () {
    if [[ ! -f "$1" ]]; then 
        echo -e "File \e[31m$1\e[0m does not exist, exiting" 
        exit 
    fi

    if [ -n "$2" ]; then 
        dir=$2
        dircheck=true 
    else 
        dir=$(echo "${1%.*}")
        dircheck=false
    fi

    while [ -d "$dir" ] 
    do 
    echo -e "Directory already exists, extracting into \e[32m$dir(2) \e[0minstead"
    dir="$dir(2)"
    done

    mkdir $dir 
    bsdtar xf$cmdh $1 -C $dir
    if $dircheck ; then 
        echo -e "Successfully extracted into \e[32m$dir\e[0m"
    else 
        echo -e "No directory given, extracted into \e[32m$dir\e[0m"
    fi
}

_help () {
    echo -e "\e[31m ===> \e[32munzip\e[0m [source] [target directory]"
}

case $1 in 
    "--help")
        _help
    ;;
    "--silent")
    cmdh=""
    _unzip $2 $3
    ;;
    *)
    cmdh="v"
    _unzip $@
    ;;
esac 


