#!/usr/bin/zsh

time=`date +%Y-%m-%d-%I-%M-%S`
geometry=`xrandr | head -n1 | cut -d',' -f2 | tr -d '[:blank:],current'`
dir="$HOME/Pictures/screenshots"
file="Screenshot_${time}_${geometry}.png"
copya () { grep -x copyq >/dev/null && echo e >/dev/null || copyq &! }
copyb () { copyq write image/png - < $dir/$file && copyq select 0 }

# notify
notify_user () {
	if [[ -e "$dir/$file" ]]; then 
		ACTION=$(dunstify -i $dir/$file --action="clicked,ACTION" "Screenshot Saved")
		case "$ACTION" in 
		"clicked")
			feh $dir/$file
			;;
		esac
	else
		dunstify "Screenshot Deleted."
	fi
}

shotwin () {
	cd ${dir} && maim -u -f png -i `xdotool getactivewindow` "$file"
	copya
	copyb
	notify_user
}

shotarea () {
#	cd ${dir} && maim -u -f png -s -b 2 -c 0.35,0.55,0.85,0.25 -l "$file"  
	cd ${dir} && maim -u -f png -s "$file"
	copya
	copyb
	notify_user
}

if [[ ! -d "$dir" ]]; then
	mkdir -p "$dir"
fi


if [[ "$1" == "--area" ]]; then
	shotarea
elif [[ "$1" == "--win" ]]; then
	shotwin
else
	echo "Available Options : --win --area"
fi

exit 0
