#!/usr/bin/zsh

grep -x copyq >/dev/null || copyq &! 

time=`date +%Y-%m-%d-%I-%M-%S`
geometry=`xrandr | head -n1 | cut -d',' -f2 | tr -d '[:blank:],current'`
dir="$HOME/Pictures/screenshots"
file="Screenshot_${time}_${geometry}.png"
copy-img () { copyq write image/png - < $dir/$file && copyq select 0 }

# notify
notify_user () {
	if [[ -e "$dir/$file" ]]; then 
		ACTION=$(dunstify -i $dir/$file --action="clicked,ACTION" 'Screenshot Saved')
		case "$ACTION" in 
		"clicked")
			feh $dir/$file
			;;
		esac
	else
		dunstify "Screenshot Deleted."
	fi
}


shotarea () {
	cd ${dir} && maim -u -f png -s "$file"
	copy-img
	notify_user
}

shotfreeze () {
	cd ${dir} && maim -u | feh -F - & maim -s "$file" 
	copy-img
	pidof feh | { read first rest ; kill $first ; }
	notify_user
}

if [[ ! -d "$dir" ]]; then
	mkdir -p "$dir"
fi


if [[ "$1" == "--area" ]]; then
	shotarea
elif [[ "$1" == "--freeze" ]]; then 
	shotfreeze
else
	echo "Available Options : --freeze --area"
fi

exit 0
