#!/usr/bin/zsh


time=`date +%Y-%m-%d-%I-%M-%S`
geometry=`xrandr | head -n1 | cut -d',' -f2 | tr -d '[:blank:],current'`
dir="$HOME/Pictures/screenshots"
mc-wname="Minecraft*"
file="Screenshot_${time}_${geometry}.png"
copy-img () { copyq write image/png - < $dir/$file && copyq select 0 }

if [[ "$(current-window.sh)" == Minecraft* ]]; then 
	dir="$HOME/.local/share/PrismLauncher/instances/wynn-1.18/.minecraft/screenshots"
	file=$(date +%Y-%m-%d_%H.%M.%S)_screenshot.png
fi 

# notify
notify_user () {
	if [ ! $(pgrep copyq) ]; then 
		dunstify "CopyQ isnt running, screenshots wont be copied to the clickboard"
	fi
	if [[ -e "$dir/$file" ]]; then 
		ACTION=$(dunstify -i $dir/$file --action="clicked,ACTION" 'Screenshot Saved')
		case "$ACTION" in 
		"clicked")
			feh $dir/$file
			;;
		esac
	else
		dunstify "Screenshot Deleted."
	fi

}

shotarea () {
	cd ${dir} && maim -u -f png -s "$file"
	copy-img
	notify_user
}

shotfreeze () {
	cd ${dir} && maim -u | feh -F - & maim -s "$file" 
	copy-img
	pidof feh | { read first rest ; kill $first ; }
	notify_user
}

imgtotxt () {
	cd $dir && maim -u -f png -s "$file"
	tesseract $file text.tmp --psm 6 -l eng txt
	copyq copy "$(cat text.tmp.txt)"
	dunstify "Text copied"
	del text.tmp.txt 
}


if [[ "$1" == "--area" ]]; then
	shotarea
elif [[ "$1" == "--freeze" ]]; then 
	shotfreeze
elif [[ "$1" == "--img-to-text" ]]; then 
	imgtotxt
elif [[ "$1" == "--deps" ]]; then 
echo 
cat << EOF
Dependencies:
	maim (screenshotting tool)
	copyq (tool used for clipboard)
	feh (used to open images/freeze option)
	dunst (for notifications)
	tesseract tesseract-data-eng (image to text tool)
EOF
echo
elif [[ "$1" == "--install-deps" ]]; then 
	echo maim copyq feh dunst tesseract-data-eng tesseract 
	sudo pacman -Sy maim copyq feh dunst tesseract-data-eng tesseract
else
echo
cat << EOF
Available Options:
	--freeze		Freezes the screen (using feh) before taking screenshot (might me weird with more than one screen)
	--area  		Takes screenshot using selection
	--img-to-text  		Image to text (experimental, might have issues with special characters)
	--deps			Lists dependencies
	--install-deps		Installs dependencies (Arch Linux)
EOF
echo
fi