#!/bin/sh

# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################

export BROWSER=firefox
#export EDITOR=nvim
export _JAVA_AWT_WM_NONREPARENTING=1 # Fix for JetBrains IDEs

pgrep -x sxhkd > /dev/null || sxhkd &

# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bspc monitor HDMI-A-0 -d 1 2 6 7 8 
bspc monitor HDMI-A-1 -d 3 4 5 9 10

rule firefox desktop=4
rule discord desktop=3
rule Variety state=floating
rule Pavucontrol state=floating
rule Lxappearance state=floating
rule Gpick state=floating
rule Nm-connection-editor state=floating

rule PolyMC desktop=6
rule lunarclient desktop=6 state=tiled 
rule Steam desktop=6
rule steam_app_1145360 desktop=6
rule steam_app_444090 desktop=6 
rule steam_proton desktop=6
rule heroic desktop=6

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

config pointer_modifier Mod4
config focus_follows_pointer true
config border_width 2
config window_gap 6
config split_ratio 0.45

# ##############################################################################
# #                                 MISCELLANEOUS                              #
# ##############################################################################

config normal_border_color 	"#44475a"
config active_border_color 	"#44475a"
config focused_border_color 	"#bd93f9"
config presel_feedback_color "#b24744"
xset m 0 0

# ##############################################################################
# #                                 STARTUP                                    #
# ##############################################################################

#variety
bash ~/.fehbg
start variety

#polybar
#sh ~/.config/polybar/launch.sh &
start multi-screens 

#picom
start picomd 

#appearance stuff
#timeout 1 lxappearance &

#keyboard layout 
start keyboard-cfg 
 
#clipman
start xfce4-clipman 

#dunst
start dunst
notify-send Bspwm Restarted -t 5000 --icon=/home/george/.config/bspwm/cat.png

#polkit 
start gnome-polkit 

#numlock
start numlockx on

#Network Applet 
start nm-applet

