#!/bin/sh

# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################

#export PATH="/home/george/scripts"
export GCM_CREDENTIAL_STORE=cache
export BROWSER=firefox
export EDITOR=code
export TERMINAL=
export _JAVA_AWT_WM_NONREPARENTING=1 # Fix for JetBrains IDEs
export DOTNET_ROOT=~/.dotnet
export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools

# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
monitor() { bspc monitor "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }
start_if() { pgrep -x $1 >/dev/null || $@ & }
startup() { pgrep -i $1 >/dev/null || $1 & }

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

config pointer_modifier Mod4
config focus_follows_pointer true
config single_monocle true
config borderless_monocle true
if [[ ! -f /tmp/borders ]]; then 
    bspc config border_width 2
    del /tmp/borders
fi 
config window_gap 0
config top_padding 30
config split_ratio 0.45
config external_rules_command "$HOME/.config/bspwm/scripts/spotify.sh"
config left_padding 0
config bottom_padding 0 

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 10 
#monitor HDMI-A-0 -d 1 2 6 7 8 
#monitor HDMI-A-1 -d 3 4 5 9 10 

rule firefox desktop=4
rule discord desktop=3
rule Variety state=floating
rule Pavucontrol state=floating
rule Lxappearance state=floating
rule Gpick state=floating
rule Nm-connection-editor state=floating
rule copyq state=floating
rule Places state=floating
rule "Primenote" state=floating
bspc rule -a floating state=floating
rule feh state=floating

rule "SkyClient (Forge 1.8.9)" desktop=2 border=off
rule MultiMC desktop=2
rule PolyMC desktop=2
rule PrismLauncher desktop=2
rule "Minecraft 1.8.9" desktop=2 border=off
rule "Minecraft 1.12.2" desktop=2 border=off
rule "Minecraft* 1.18.2" desktop=2 border=off
rule "Minecraft* 1.19.3" desktop=2 border=off
rule lunarclient desktop=2
rule Steam desktop=2 q
rule steam_app_1145360 desktop=2 border=off 
rule steam_app_444090 desktop=2
rule steam_app_960090 desktop=2 
rule steam_proton desktop=2
rule heroic desktop=2
rule PortalWars-Linux-Shipping desktop=2 border=off 
rule Lutris desktop=2 

rule afk-1 desktop=8
rule afk-2 desktop=10

# ##############################################################################
# #                                 MISCELLANEOUS                              #
# ##############################################################################

config normal_border_color 	"#44475a"
config active_border_color 	"#44475a"
config focused_border_color 	"#b4befe"
config presel_feedback_color "#b24744"

# ##############################################################################
# #                                 STARTUP                                    #
# ##############################################################################

#variety
bash ~/.fehbg &

#weather 
ntfd &

#polybar
exec ~/.config/polybar/scripts/multi-screens.sh &

#picom
#pgrep -x picom >/dev/null || picom --config ~/.config/picom/config.conf --experimental-backends &
start_if picom --config ~/.config/picom/config.conf --experimental-backends

#mouse settings 
xsetroot -cursor_name left_ptr &
xinput set-prop 'Mice&MultiKB USB product Mice&MultiKB USB product' 'libinput Accel Speed' -0.8

#keyboard layout 
setxkbmap -layout us,gr &
$HOME/.config/bspwm/keyboard-colors &
#g512-led -fx cwave keys 1a

#clipman
start clipmenud
start greenclip daemon
pgrep -x copyq >/dev/null || copyq & 

#dunst
start dunst 
dunstify "Restarted" -a Bspwm -t 2000 --icon=/home/george/.config/bspwm/restart_icon.png 
#if [ -d /usr/share/icons/default ]; then dunstify -t 15000 "/usr/share/icons/default exists, cursor theme might not work properly" --icon=/home/george/.icons/Papirus-Dark/32x32/categories/bell.svg; fi


#polkit 
start gnome-polkit 

#numlock
numlockx on

#Network Applet 
start nm-applet

#sxhkd
start sxhkd -c ~/.config/bspwm/sxhkdrc

#brightness
brightness-set $(cat /tmp/brightness-value) &
#brightness-set 1 
#volume up 


## Autostart ##
startup discord 


while true; do sleep 1; if [[ ! $(cat /tmp/polybarDataSpotify) == $(playerctl --player=spotify metadata -f '{{artist}} - {{title}}')  ]]; then echo "" > /tmp/polybarIconSpotify; polybar-msg action "#playerctl-spotify.hook.0" > /dev/null; fi; done &

