#!/bin/sh

# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################

export BROWSER=firefox
#export EDITOR=nvim
export _JAVA_AWT_WM_NONREPARENTING=1 # Fix for JetBrains IDEs

pgrep -x sxhkd > /dev/null || sxhkd &

# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bspc monitor HDMI-A-0 -d 1 2 6 7 8 
bspc monitor HDMI-A-1 -d 3 4 5 9 10

rule firefox desktop=4
rule discord desktop=3
rule Variety state=floating
rule Pavucontrol state=floating
rule Lxappearance state=floating
rule Gpick state=floating
rule Nm-connection-editor state=floating

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

config pointer_modifier Mod4
bspc config focus_follows_pointer true
bspc config border_width 2
config window_gap 6
config split_ratio 0.45

# ##############################################################################
# #                                 MISCELLANEOUS                              #
# ##############################################################################

bspc config normal_border_color 	"#44475a"
bspc config active_border_color 	"#44475a"
bspc config focused_border_color 	"#bd93f9"
bspc config presel_feedback_color "#b24744"
xset m 0 0

# ##############################################################################
# #                                 STARTUP                                    #
# ##############################################################################

#variety
bash ~/.fehbg
pgrep -x variety >/dev/null && echo "e" >/dev/null || variety &

#polybar
#bash ~/.config/polybar/launch.sh &
bash ~/.config/polybar/scripts/multi-screens.sh &

#picom
picom --config ~/.config/picom/config.conf --experimental-backends &

#appearance stuff
timeout 1 lxappearance &

#keyboard layout 
setxkbmap -layout us,gr &
setxkbmap -option 'grp:alt_shift_toggle' &

#clipman
pgrep -x xfce4-clipman >/dev/null && echo e >/dev/null || xfce4-clipman &

#dunst
pgrep -x dunst >/dev/null && pkill dunst || dunst --config $HOME/.config/dunst/dunstrc &
dunst --config $HOME/.config/dunst/dunstrc &

#polkit 
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#numlock
numlockx on

# Network Applet 
nm-applet
