#!/bin/bash
# Tiny colored fetch script



f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
d=$'\e[1m'
t=$'\e[0m'
v=$'\e[7m'

# Items
h=wm
wmname="$(xprop -id $(xprop -root -notype | awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}') -notype -f _NET_WM_NAME 8t | grep "WM_NAME" | cut -f2 -d \")"

k=kr
kernel="$(uname -r | cut -d '-' -f1)"

sh=sh
shell=$(basename $SHELL)

o=os
os="$(uname -s)"

p=pk
pk="$(pacman -Q | wc -l)"

u=up
up="$(awk '{print int($1/3600)"h:"int(($1%3600)/60)"m"}' /proc/uptime)"

cat << EOF

  ／|、        $f3$o $t~ arch 
（ﾟ､ ｡ 7       $f1$u $t~ $up
  l、  ~ヽ     $f6$h $t~ $wmname
  じしf_, )ノ  $f5$p $t~ $pk

EOF
