#!/bin/bash
# You can call this script like this:
# $./volume up
# $./volume down
# $./volume mute

DIR="$HOME/.config/dunst/icons"

function get_volume {
      amixer -D pipewire get Master | grep '%' | head -n 1 | awk -F'[' '{print $2}' | awk -F'%' '{print $1}'
}

function is_mute {
      amixer -D pipewire get Master | grep '%' | grep -oE '[^ ]+$' | grep off
}

function return_volume {
  volume=`get_volume`
  if is_mute >/dev/null; then
    echo "%{F#ed8796} Muted"
  elif [  "$volume" -lt "10" ]; then
    echo "$volume%"
  elif [ "$volume" -lt "30" ]; then
    echo " $volume%"
  elif [ "$volume" -lt "50" ]; then
    echo " $volume%"
  else 
    echo " $volume%"
  fi
}

function send_notification {
  volume=`get_volume`
  bar=$(seq -s "─" 0 $(($volume / 5)) | sed 's/[0-9]//g')
  if [ "$volume" = "0" ]; then
    icon_name="$DIR/volume-muted.svg"
    bar=""
  elif [  "$volume" -lt "10" ]; then
    icon_name="$DIR/volume-low.svg"
  elif [ "$volume" -lt "30" ]; then
    icon_name="$DIR/volume-low.svg"
  elif [ "$volume" -lt "45" ]; then
    icon_name="$DIR/volume-medium.svg"
  else
    icon_name="$DIR/volume-high.svg"
  fi
  dunstify "Volume" -t 3000 -i $icon_name -r 5555 -u normal -h int:value:$(($volume))
}

case $1 in
  up)
	  amixer -D pipewire set Master on > /dev/null
	  amixer -D pipewire set Master 2%+ > /dev/null
    send_notification
    polybar-msg action "#pipewire.hook.0"
    ;;
  down)
	  amixer -D pipewire set Master on > /dev/null
	  amixer -D pipewire set Master 2%- > /dev/null
    send_notification
    polybar-msg action "#pipewire.hook.0"
    ;;
  mute)
	  amixer -D pipewire set Master 1+ toggle > /dev/null
    if is_mute ; then
      icon_name="$DIR/volume-muted.svg"
      dunstify "Mute" -t 3000 -i $icon_name -r 5555 -u normal -h int:value:0 
    else
      send_notification
    fi
    polybar-msg action "#pipewire.hook.0"
    ;;
  get)
    return_volume
esac
